version: "3.9"

services:
  db:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=sprow
#      - MONGO_INITDB_ROOT_PASSWORD=12345

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'fat_rabbit'
    environment:
      - RABBITMQ_DEFAULT_USER=sprow
      - RABBITMQ_DEFAULT_PASS=12345
    ports:
      - "5672:5672"
      - "15672:15672"

  content_task:
    restart: always
    build:
      context: ./content_task
      dockerfile: Dockerfile
    depends_on:
      - "rabbitmq"
    networks:
      - default
    ports:
      - "8081:8081"


  content_scraper:
    restart: always
    build:
      context: ./content_scraper
      dockerfile: Dockerfile
    depends_on:
      - "db"
      - "rabbitmq"
      - "content_task"
    networks:
      - default
    ports:
      - "8082:8082"

volumes:
  data: