###

POST  http://127.0.0.1:8081
Content-Type: application/json

{
  "url": "https://www.meteoprog.ua/ru/"
}

### TODO после записи в моного scraper должен рапортовать об успехе в Rabbit -> написать парсер

### BAD URL

POST  http://127.0.0.1:8081
Content-Type: application/json

{
  "url": "google.com"
}

###

### BAD URL

POST  http://127.0.0.1:8085
Content-Type: application/json

{
  "url": ""
}

###